name: Jest Test

on:
  workflow_run:
    workflows: ["Eslint Test"]
    types:
      - completed

jobs:
  "run-jest-tests":
    runs-on: self-hosted
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
