name: Prepare Database

on:
  push:
    branches:
      - deploy

  pull_request:
    branches:
      - deploy

jobs:
  "set-up-sample-data":
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove Database
        run: npx ts-node scripts/remove_db.ts mongodb://127.0.0.1:27017/fake_so
      
      - name: Insert Sample Data
        run: npx ts-node scripts/populate_db.ts mongodb://127.0.0.1:27017/fake_so
