name: CI

on:
  push:
    branches:
      - main
      - deploy

  pull_request:
    branches:
      - deploy
      - main

jobs:
  "run-jest-tests":
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
          echo "TEST_USER_PW=${{ secrets.TEST_USER_PW }}" > .env

      - name: Run Tests
        run: npm run test

  "run-bdd-tests":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install
      
      - name: Create Server .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env
          echo "TEST_USER_PW=${{ secrets.TEST_USER_PW }}" > .env

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Start Server in Background
        working-directory: ./server
        run: |
          NODE_ENV=test npx ts-node server.ts &
          # Save the PID so we can kill the server later
          echo $! > server_pid.txt
          # Give the server time to start
          sleep 5

      - name: Run BDD Tests
        working-directory: ./client
        run: npm run test

      - name: Shutdown Server
        working-directory: ./server
        run: |
          if [ -f server_pid.txt ]; then
            kill $(cat server_pid.txt)
          fi