name: CI

on:
  push:
    branches:
      - main
      - deploy

  pull_request:
    branches:
      - deploy
      - main

jobs:
  "run-jest-tests":
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" | tr -d '\n' > .env
          echo "TEST_USER_PW=${{ secrets.TEST_USER_PW }}" | tr -d '\n' >> .env

      - name: Run Tests
        run: npm run test

  "run-bdd-tests":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install
      
      - name: Create Server .env file
        working-directory: ./server
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" | tr -d '\n' > .env
          echo "TEST_USER_PW=${{ secrets.TEST_USER_PW }}" | tr -d '\n' >> .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          install-command: npm install
          start: npm start
          component: true
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          cache-key: ''
