name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  "run-bdd-tests":
    runs-on: self-hosted
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TEST_USER_PW: ${{ secrets.TEST_USER_PW }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Start MongoDB via brew
        run: |
          brew services start mongodb-community@8.0
          sleep 5
      
      - name: Check MongoDB Status
        run: |
          nc -zv 127.0.0.1 27017

      - name: Start Server in Background
        working-directory: ./server
        run: |
          NODE_ENV=test npx ts-node server.ts &
          echo $! > ../server_pid.txt
          sleep 5

      - name: Start Client in Background
        working-directory: ./client
        run: |
          npm start > client.log 2>&1 &
          echo $! > ../client_pid.txt

      - name: Wait for Client to be Ready
        run: |
          npm install -g wait-on
          wait-on http://localhost:3000

      - name: Run BDD Tests
        working-directory: ./client
        run: npx cypress run --headless --no-sandbox --disable-gpu

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: client/cypress

      - name: Shutdown Server and Client
        run: |
          if [ -f server/server_pid.txt ]; then kill $(cat server/server_pid.txt); fi
          if [ -f client/client_pid.txt ]; then kill $(cat client_pid.txt); fi