name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # start MongoDB
      - name: Start MongoDB via brew
        run: |
          brew services start mongodb-community@8.0
          sleep 5

      # Install server dependencies and populate DB
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Populate database
        working-directory: ./server
        run: |
          npx ts-node scripts/remove_db.ts mongodb://127.0.0.1:27017/fake_so
          npx ts-node scripts/populate_db.js mongodb://127.0.0.1:27017/fake_so

      # Start server in background
      - name: Start server
        working-directory: ./server
        run: |
          NODE_ENV=test npm start &
          sleep 5

      # Install client dependencies
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # Start client in background (if needed for the tests)
      - name: Start Client in Background
        working-directory: ./client
        run: |
          npm start > client.log 2>&1 &
          echo $! > ../client_pid.txt

      - name: Wait for Client to be Ready
        run: |
          npm install -g wait-on
          wait-on http://localhost:3000

      # Run Cypress tests
      - name: Run Cypress tests
        working-directory: ./client
        run: npm run test

      - name: Shutdown Server and Client
        run: |
          if [ -f server/server_pid.txt ]; then kill $(cat server/server_pid.txt); fi
          if [ -f client_pid.txt ]; then kill $(cat client_pid.txt); fi
