name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install MongoDB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "6.0"
          mongodb-port: 27017

      # Install server dependencies and populate DB
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Populate database
        working-directory: ./server
        run: |
          npx ts-node scripts/remove_db.ts mongodb://127.0.0.1:27017/fake_so
          npx ts-node scripts/populate_db.js mongodb://127.0.0.1:27017/fake_so

      # Start server in background
      - name: Start server
        working-directory: ./server
        run: |
          NODE_ENV=test npm start &
          sleep 5

      # Install client dependencies
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # Start client in background (if needed for the tests)
      - name: Start client
        working-directory: ./client
        run: |
          npm start &
          sleep 10

      # Run Cypress tests
      - name: Run Cypress tests
        working-directory: ./client
        run: npm run test
